apiVersion: v1
kind: Secret
metadata:
  name: todo-db-secret
  labels:
    app: todo-app
    component: web
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.database.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.database.password | quote }}
