apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  labels:
    app: todo-app
    component: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
      component: web
  template:
    metadata:
      labels:
        app: todo-app
        component: web
    spec:
      containers:
        - name: todo-app
          image: skyber2/ipr-lab-3:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
          envFrom:
            - configMapRef:
                name: todo-config
            - secretRef:
                name: todo-db-secret
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
