apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: todo-app
  labels:
    app: todo-app
    component: web
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: todo-app
      component: web
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
