image:
  repository: postgres
  tag: 15-alpine
  pullPolicy: IfNotPresent

database:
  name: todo_app
  user: postgres
  password: change_me

service:
  name: postgres
  port: 5432

storage:
  size: 1Gi

resources: {}
