apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: todo-matrix
  labels:
    app: todo-app
    component: database
spec:
  type: ClusterIP
  selector:
    app: todo-app
    component: database
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432