apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-config
  labels:
    app: todo-app
    component: web
data:
  POSTGRES_DB: {{ .Values.database.name | quote }}
  POSTGRES_HOST: {{ .Values.database.host | quote }}
  POSTGRES_PORT: {{ .Values.database.port | quote }}
  OTEL_SERVICE_NAME: {{ .Values.observability.serviceName | quote }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.observability.otlpEndpoint | quote }}
