apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: todo-matrix
resources:
  - namespace.yaml
  - ../../base
patches:
  - path: service-nodeport-patch.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: todo-config
    literals:
      - POSTGRES_DB=todo_app
      - POSTGRES_HOST=postgres-0.postgres
      - POSTGRES_PORT=5432
      - OTEL_SERVICE_NAME=todo-matrix-app
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo.observability.svc.cluster.local:4318
secretGenerator:
  - name: todo-db-secret
    type: Opaque
    literals:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=change_me_dev
